### ISSUE TITLE
Publish on Terraform Registry (and tag version)

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/aws-ecs-gitlab#2]

**Comment by phuonghuynh** [comment]
@ronaldtse I not have permission to publish release for this one

**Comment by phuonghuynh** [comment]
Got this error from Terraform Registry

> Error creating the webhook. Please ensure you have admin permissions on the GitHub repository and then try again.

**Comment by ronaldtse** [comment]
Released. Thanks @phuonghuynh !
